# Generated by Django 5.1.1 on 2024-10-08 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_article_category_remove_article_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='background_color',
        ),
    ]
